import type { Font as FontkitFont } from "fontkit";
import type PDFKit from "pdfkit";
import PDFDocument from "pdfkit";
import {
  detectLanguages,
  type LanguageSupportResult,
  reportAllLanguages,
} from "@/lib/font-language-detection";
import {
  buildFontDetailFields,
  buildFontSummaryFields,
  extractFontMetadata,
  type FontMetadata,
  formatFileSize,
} from "@/lib/font-metadata";
import {
  type LanguageSupportSummary,
  summarizeSupport,
} from "@/lib/font-report";

export interface FontReport {
  fileSizeBytes: number;
  generatedAt: string;
  languages: LanguageSupportResult[];
  metadata: FontMetadata;
  summary: LanguageSupportSummary;
}

export function buildFontReport(
  font: FontkitFont,
  fontData: ArrayBuffer | undefined,
  fileName: string,
  mode: "all" | "detected" = "all",
  fileSizeBytes?: number
): FontReport {
  const languages =
    mode === "all"
      ? reportAllLanguages(font, fontData)
      : detectLanguages(font, fontData);

  return {
    generatedAt: new Date().toISOString(),
    metadata: extractFontMetadata(font, fileName),
    fileSizeBytes: fileSizeBytes ?? fontData?.byteLength ?? 0,
    languages,
    summary: summarizeSupport(languages),
  };
}

export function exportReportAsJson(report: FontReport): string {
  return JSON.stringify(report, null, 2);
}

const SUPPORT_LABELS: Record<LanguageSupportResult["support"], string> = {
  full: "Full support",
  decomposed: "Supported via combining marks",
  "positioning-failed": "Glyphs present, positioning failed",
  none: "Not supported",
};

const PDF = {
  accent: "#2d6a4f",
  border: "#e5e7eb",
  ink: "#111827",
  muted: "#6b7280",
  pageBottom: 760,
  surface: "#f9fafb",
  warning: "#b45309",
} as const;

const MARGIN = 50;
const PAGE_WIDTH = 595.28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const FLOW_LEFT = {
  align: "left" as const,
  width: CONTENT_WIDTH,
};

function syncTextCursor(doc: PDFKit.PDFDocument): void {
  doc.x = MARGIN;
}

function flowText(
  doc: PDFKit.PDFDocument,
  text: string,
  options?: PDFKit.Mixins.TextOptions
): PDFKit.PDFDocument {
  syncTextCursor(doc);
  return doc.text(text, { ...FLOW_LEFT, ...options });
}

function summarizeScripts(
  languages: LanguageSupportResult[]
): string | undefined {
  const scripts = [...new Set(languages.map((lang) => lang.script))].toSorted();
  if (scripts.length === 0) {
    return;
  }
  if (scripts.length <= 8) {
    return scripts.join(", ");
  }
  return `${scripts.slice(0, 8).join(", ")} +${scripts.length - 8} more`;
}

function formatGeneratedAt(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
  if (doc.y + needed > PDF.pageBottom) {
    doc.addPage();
    syncTextCursor(doc);
  }
}

function drawPageFooter(doc: PDFKit.PDFDocument, fileName: string): void {
  const footerY = PDF.pageBottom + 24;
  doc
    .font("Helvetica")
    .fontSize(7.5)
    .fillColor(PDF.muted)
    .text(fileName, MARGIN, footerY, {
      align: "left",
      lineBreak: false,
      width: CONTENT_WIDTH / 2,
    })
    .text("Generated by Sora Type", MARGIN, footerY, {
      align: "right",
      lineBreak: false,
      width: CONTENT_WIDTH,
    });
}

function drawReportHeader(doc: PDFKit.PDFDocument, report: FontReport): void {
  const { metadata } = report;

  doc.font("Helvetica-Bold").fontSize(9).fillColor(PDF.accent);
  flowText(doc, "SORA TYPE", { characterSpacing: 1.2 });
  doc.font("Helvetica").fontSize(8).fillColor(PDF.muted);
  flowText(doc, "Font Inspection Report");
  doc.moveDown(0.8);

  doc.font("Helvetica-Bold").fontSize(22).fillColor(PDF.ink);
  flowText(doc, metadata.fullName);
  doc.moveDown(0.15);

  doc.font("Helvetica").fontSize(11).fillColor(PDF.muted);
  flowText(doc, `${metadata.familyName} · ${metadata.style}`);
  doc.moveDown(0.35);

  doc.fontSize(9);
  flowText(
    doc,
    `${metadata.format.toUpperCase()} · ${formatFileSize(report.fileSizeBytes)} · ${metadata.numGlyphs.toLocaleString()} glyphs · ${formatGeneratedAt(report.generatedAt)}`
  );
  doc.moveDown(0.6);

  const ruleY = doc.y;
  doc
    .strokeColor(PDF.border)
    .lineWidth(1)
    .moveTo(MARGIN, ruleY)
    .lineTo(PAGE_WIDTH - MARGIN, ruleY)
    .stroke();
  doc.moveDown(0.75);
}

function drawStatCards(
  doc: PDFKit.PDFDocument,
  summary: LanguageSupportSummary
): void {
  ensureSpace(doc, 72);
  const gap = 10;
  const cardWidth = (CONTENT_WIDTH - gap * 3) / 4;
  const cardHeight = 54;
  const startY = doc.y;

  const stats = [
    { color: PDF.accent, label: "Full support", value: summary.full },
    { color: "#2563eb", label: "Decomposed", value: summary.decomposed },
    {
      color: PDF.warning,
      label: "Positioning failed",
      value: summary.positioningFailed,
    },
    { color: PDF.muted, label: "Unsupported", value: summary.none },
  ];

  let x = MARGIN;
  for (const stat of stats) {
    doc
      .roundedRect(x, startY, cardWidth, cardHeight, 6)
      .fillAndStroke(PDF.surface, PDF.border);

    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .fillColor(stat.color)
      .text(String(stat.value), x + 12, startY + 10, {
        lineBreak: false,
        width: cardWidth - 24,
      });

    doc
      .font("Helvetica")
      .fontSize(7.5)
      .fillColor(PDF.muted)
      .text(stat.label, x + 12, startY + 34, {
        width: cardWidth - 24,
      });

    x += cardWidth + gap;
  }

  doc.y = startY + cardHeight + 14;
  syncTextCursor(doc);
  doc
    .font("Helvetica")
    .fontSize(8.5)
    .fillColor(PDF.muted)
    .text(`${summary.total.toLocaleString()} languages checked`, {
      align: "right",
      width: CONTENT_WIDTH,
    });
  syncTextCursor(doc);
  doc.moveDown(0.5);
}

function drawSectionTitle(doc: PDFKit.PDFDocument, title: string): void {
  ensureSpace(doc, 36);
  syncTextCursor(doc);
  doc.moveDown(0.35);
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(PDF.ink)
    .text(title, FLOW_LEFT);

  const ruleY = doc.y + 2;
  doc
    .strokeColor(PDF.border)
    .lineWidth(0.75)
    .moveTo(MARGIN, ruleY)
    .lineTo(PAGE_WIDTH - MARGIN, ruleY)
    .stroke();
  doc.y = ruleY + 10;
  syncTextCursor(doc);
}

function drawDetailRow(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string
): void {
  const labelWidth = 132;
  const valueWidth = CONTENT_WIDTH - labelWidth - 8;
  const valueHeight = doc.heightOfString(value, {
    width: valueWidth,
  });

  ensureSpace(doc, Math.max(16, valueHeight + 6));

  const startY = doc.y;
  doc
    .font("Helvetica")
    .fontSize(8.5)
    .fillColor(PDF.muted)
    .text(label, MARGIN, startY, { align: "left", width: labelWidth });

  doc
    .font("Helvetica")
    .fontSize(8.5)
    .fillColor(PDF.ink)
    .text(value, MARGIN + labelWidth + 8, startY, {
      align: "left",
      width: valueWidth,
    });

  doc.y = startY + Math.max(12, valueHeight) + 5;
  syncTextCursor(doc);
}

function drawDetailSection(
  doc: PDFKit.PDFDocument,
  title: string,
  fields: Array<{ label: string; value: string }>
): void {
  if (fields.length === 0) {
    return;
  }

  drawSectionTitle(doc, title);
  for (const field of fields) {
    drawDetailRow(doc, field.label, field.value);
  }
}

function drawWrappedParagraph(
  doc: PDFKit.PDFDocument,
  text: string,
  options?: { color?: string; fontSize?: number; gap?: number }
): void {
  const fontSize = options?.fontSize ?? 8.5;
  const height = doc.heightOfString(text, {
    width: CONTENT_WIDTH,
  });

  ensureSpace(doc, height + (options?.gap ?? 8));
  syncTextCursor(doc);
  doc
    .font("Helvetica")
    .fontSize(fontSize)
    .fillColor(options?.color ?? PDF.ink)
    .text(text, { ...FLOW_LEFT, lineGap: 2 });
  doc.moveDown(options?.gap ? options.gap / 12 : 0.35);
}

function drawTagBlock(
  doc: PDFKit.PDFDocument,
  title: string,
  tags: string[],
  emptyLabel: string
): void {
  drawSectionTitle(doc, title);

  if (tags.length === 0) {
    drawWrappedParagraph(doc, emptyLabel, { color: PDF.muted });
    return;
  }

  drawWrappedParagraph(doc, tags.join("  ·  "), { fontSize: 8, gap: 10 });
}

function drawVariationAxes(
  doc: PDFKit.PDFDocument,
  axes: FontMetadata["variationAxes"]
): void {
  if (axes.length === 0) {
    return;
  }

  drawSectionTitle(doc, "Variation axes");

  for (const axis of axes) {
    drawDetailRow(
      doc,
      `${axis.tag} (${axis.name})`,
      `${axis.min} → ${axis.default} → ${axis.max}`
    );
  }
}

function languageSuffix(support: LanguageSupportResult["support"]): string {
  if (support === "decomposed") {
    return "*";
  }
  if (support === "positioning-failed") {
    return "†";
  }
  return "";
}

function drawLanguageGroup(
  doc: PDFKit.PDFDocument,
  title: string,
  languages: LanguageSupportResult[],
  options?: { showUnpositioned?: boolean }
): void {
  if (languages.length === 0) {
    return;
  }

  ensureSpace(doc, 28);
  syncTextCursor(doc);
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(PDF.ink)
    .text(`${title} (${languages.length})`, FLOW_LEFT)
    .moveDown(0.2);

  if (options?.showUnpositioned) {
    for (const lang of languages) {
      ensureSpace(doc, 28);
      syncTextCursor(doc);
      doc
        .font("Helvetica-Bold")
        .fontSize(8.5)
        .fillColor(PDF.ink)
        .text(`${lang.name} (${lang.code}, ${lang.script})`, FLOW_LEFT);

      if (lang.unpositioned.length > 0) {
        syncTextCursor(doc);
        doc
          .font("Helvetica")
          .fontSize(8)
          .fillColor(PDF.warning)
          .text(`Unpositioned marks: ${lang.unpositioned.join(", ")}`, {
            ...FLOW_LEFT,
            lineGap: 1.5,
          });
      }

      doc.moveDown(0.25);
    }
    return;
  }

  const compact = languages
    .map((lang) => {
      const suffix = languageSuffix(lang.support);
      return `${lang.name} (${lang.code}, ${lang.script}${suffix})`;
    })
    .join(" · ");

  drawWrappedParagraph(doc, compact, { fontSize: 8, gap: 12 });

  const hasDecomposed = languages.some((lang) => lang.support === "decomposed");
  if (hasDecomposed) {
    syncTextCursor(doc);
    doc
      .font("Helvetica")
      .fontSize(7.5)
      .fillColor(PDF.muted)
      .text(
        "* supported via combining marks, not a precomposed glyph",
        FLOW_LEFT
      )
      .moveDown(0.25);
  }
}

function drawMetricsGrid(
  doc: PDFKit.PDFDocument,
  metadata: FontMetadata
): void {
  drawSectionTitle(doc, "Font metrics");

  const metrics = metadata.metrics;
  const rows = [
    ["Units per em", String(metrics.unitsPerEm)],
    ["Ascender", String(metrics.ascent)],
    ["Descender", String(metrics.descent)],
    ["Line gap", String(metrics.lineGap)],
    ["Cap height", String(metrics.capHeight)],
    ["x-height", String(metrics.xHeight)],
    ["Italic angle", String(metrics.italicAngle)],
    ["Underline position", String(metrics.underlinePosition)],
    ["Underline thickness", String(metrics.underlineThickness)],
  ];

  const colWidth = CONTENT_WIDTH / 3;
  const cellHeight = 34;
  ensureSpace(doc, cellHeight * 3 + 8);
  const startY = doc.y;

  for (const [index, [label, value]] of rows.entries()) {
    const col = index % 3;
    const row = Math.floor(index / 3);
    const x = MARGIN + col * colWidth;
    const y = startY + row * cellHeight;

    doc
      .roundedRect(x, y, colWidth - 8, cellHeight - 6, 4)
      .fillAndStroke(PDF.surface, PDF.border);

    doc
      .font("Helvetica")
      .fontSize(7)
      .fillColor(PDF.muted)
      .text(label, x + 10, y + 8, { width: colWidth - 20 });

    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor(PDF.ink)
      .text(value, x + 10, y + 18, { width: colWidth - 20 });
  }

  doc.y = startY + cellHeight * 3 + 8;
  syncTextCursor(doc);
}

export function exportReportAsPdf(report: FontReport): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: MARGIN,
      info: {
        Author: "Sora Type",
        Subject: "Font language support report",
        Title: `${report.metadata.fullName} — Font Report`,
      },
      size: "A4",
    });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on("error", reject);

    const { metadata, summary } = report;
    const scriptSummary = summarizeScripts(report.languages);
    const summaryFields = buildFontSummaryFields(metadata, scriptSummary);
    const detailFields = buildFontDetailFields(metadata);

    const supported = report.languages.filter(
      (lang) => lang.support !== "none"
    );
    const fullSupport = supported.filter((lang) => lang.support === "full");
    const decomposed = supported.filter(
      (lang) => lang.support === "decomposed"
    );
    const positioningFailed = supported.filter(
      (lang) => lang.support === "positioning-failed"
    );
    const unsupported = report.languages.filter(
      (lang) => lang.support === "none"
    );

    drawReportHeader(doc, report);
    drawStatCards(doc, summary);

    drawDetailSection(doc, "Overview", [
      { label: "File name", value: metadata.fileName },
      { label: "Format", value: metadata.format.toUpperCase() },
      { label: "PostScript name", value: metadata.postscriptName },
      { label: "Weight", value: metadata.weightLabel },
      { label: "Width", value: metadata.widthLabel },
      { label: "Embedding", value: metadata.embeddingSummary },
      ...summaryFields.map((field) => ({
        label: field.label,
        value: field.value,
      })),
    ]);

    const legalFields = detailFields.filter((field) =>
      [
        "Designer",
        "Manufacturer",
        "Description",
        "License",
        "License URL",
        "Copyright",
        "Trademark",
        "Designer URL",
        "Vendor URL",
      ].includes(field.label)
    );

    drawDetailSection(doc, "Design & legal", legalFields);
    drawMetricsGrid(doc, metadata);

    drawTagBlock(
      doc,
      `OpenType features (${metadata.openTypeFeatures.length})`,
      metadata.openTypeFeatures,
      "No GSUB/GPOS feature tags detected."
    );

    drawTagBlock(
      doc,
      `Raw tables (${metadata.tables.length})`,
      metadata.tables,
      "No OpenType tables found."
    );

    drawVariationAxes(doc, metadata.variationAxes);

    drawSectionTitle(doc, "Language support");
    drawLanguageGroup(doc, "Full support", fullSupport);
    drawLanguageGroup(doc, "Decomposed support", decomposed);
    drawLanguageGroup(doc, "Positioning issues", positioningFailed, {
      showUnpositioned: true,
    });

    if (unsupported.length > 0) {
      ensureSpace(doc, 24);
      syncTextCursor(doc);
      doc
        .font("Helvetica-Bold")
        .fontSize(10)
        .fillColor(PDF.ink)
        .text(`Unsupported (${unsupported.length})`, FLOW_LEFT)
        .moveDown(0.15);

      if (unsupported.length <= 40) {
        drawWrappedParagraph(
          doc,
          unsupported
            .map((lang) => `${lang.name} (${lang.code}, ${lang.script})`)
            .join(" · "),
          { color: PDF.muted, fontSize: 8, gap: 10 }
        );
      } else {
        drawWrappedParagraph(
          doc,
          `${unsupported.length} languages are not supported by this font. Export JSON for the full list.`,
          { color: PDF.muted, fontSize: 8.5, gap: 10 }
        );
      }
    }

    drawSectionTitle(doc, "Support legend");
    for (const [level, label] of Object.entries(SUPPORT_LABELS)) {
      drawDetailRow(doc, label, level);
    }

    const pageRange = doc.bufferedPageRange();
    for (
      let page = pageRange.start;
      page < pageRange.start + pageRange.count;
      page++
    ) {
      doc.switchToPage(page);
      drawPageFooter(doc, metadata.fileName);
    }

    doc.end();
  });
}
