/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\matcha\matchaTheme.ts
 * Command: astryx theme build src\themes\matcha\matchaTheme.ts
 * Generated: 2026-07-04T20:14:08.754Z
 */

import type { IconRegistry } from "@astryxdesign/core/Icon";
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const matchaIconRegistry: IconRegistry;
export declare const matchaTheme: DefinedTheme;
